### ISSUE TITLE
installing nlsam on centos

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/nlsam#99]
when trying to install nlsam on Centos the following error appears:
```
pip install nlsam_0.6.1_centos6_x64.zip --user rosella
Processing ./nlsam_0.6.1_centos6_x64.zip
    ERROR: Command errored out with exit status 1:
     command: /home/rosella/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-p5dlbqnh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-p5dlbqnh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e5y0g4co
         cwd: /tmp/pip-req-build-p5dlbqnh/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rosella/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-p5dlbqnh/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
what shoud it be due to? I have python 3.7.3 installed with conda package.
My OS features are:
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

Thanks,
Rosella

**Comment by samuelstjean** [comment]
This is because the zip file has all the files precompiled in it, you can just unpack the archive and run the content as is, on anything more recent than cent os 6 (so pretty much anything). If you want to install and compile it yourself though, you can do so from the source, the zip has everything already done for you normally (although with old stuff likely).

**Comment by rosella1234** [comment]
thank you.
I then passed to install the master version, since I need the 'auto' option for denoising 
`pip install https://github.com/samuelstjean/nlsam/archive/master.zip`
but the following error occurs:
```
Collecting https://github.com/samuelstjean/nlsam/archive/master.zip
  Using cached https://github.com/samuelstjean/nlsam/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: joblib>=0.14.1 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (1.0.0)
Collecting spams@ https://github.com/samuelstjean/spams-python/releases/download/v2.6.1/spams-2.6.tar.gz#egg=spams-2.6
  Downloading https://github.com/samuelstjean/spams-python/releases/download/v2.6.1/spams-2.6.tar.gz (762 kB)
     |████████████████████████████████| 762 kB 8.6 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cython>=0.29 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (0.29.21)
Requirement already satisfied: scipy>=0.19.1 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (1.5.2)
Requirement already satisfied: autodmri>=0.2.1 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (0.2.5)
Requirement already satisfied: dipy>=0.11 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (1.4.0)
Requirement already satisfied: numpy>=1.15.4 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (1.19.2)
Requirement already satisfied: nibabel>=2.0 in ./anaconda3/lib/python3.7/site-packages (from nlsam==0.6.1) (3.2.1)
Requirement already satisfied: Pillow>=6.0 in ./anaconda3/lib/python3.7/site-packages (from spams@ https://github.com/samuelstjean/spams-python/releases/download/v2.6.1/spams-2.6.tar.gz#egg=spams-2.6->nlsam==0.6.1) (8.1.0)
Requirement already satisfied: tqdm>=4.30.0 in ./anaconda3/lib/python3.7/site-packages (from dipy>=0.11->nlsam==0.6.1) (4.55.1)
Requirement already satisfied: h5py>=2.5.0 in ./anaconda3/lib/python3.7/site-packages (from dipy>=0.11->nlsam==0.6.1) (2.10.0)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from h5py>=2.5.0->dipy>=0.11->nlsam==0.6.1) (1.15.0)
Requirement already satisfied: packaging>=14.3 in ./anaconda3/lib/python3.7/site-packages (from nibabel>=2.0->nlsam==0.6.1) (20.8)
Requirement already satisfied: pyparsing>=2.0.2 in ./anaconda3/lib/python3.7/site-packages (from packaging>=14.3->nibabel>=2.0->nlsam==0.6.1) (2.4.7)
Building wheels for collected packages: spams
  Building wheel for spams (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rosella/anaconda3/bin/python /home/rosella/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp_0wkr1c5
       cwd: /tmp/pip-install-fgsoi9h0/spams_dac72f5c5bd94ece91192ea2af811ffa
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/spams
  copying spams/__init__.py -> build/lib.linux-x86_64-3.7/spams
  copying spams/spams.py -> build/lib.linux-x86_64-3.7/spams
  creating build/lib.linux-x86_64-3.7/spams_wrap
  copying spams_wrap/__init__.py -> build/lib.linux-x86_64-3.7/spams_wrap
  copying spams_wrap/spams_wrap.py -> build/lib.linux-x86_64-3.7/spams_wrap
  running build_ext
  building 'spams_wrap._spams_wrap' extension
  C compiler: gcc -pthread -B /home/rosella/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/spams_wrap
  compile options: '-Ispams_wrap -Ispams_wrap/linalg -Ispams_wrap/prox -Ispams_wrap/decomp -Ispams_wrap/dictLearn -I/tmp/pip-build-env-5t4ly4vk/overlay/lib/python3.7/site-packages/numpy/core/include -I/home/rosella/anaconda3/include/python3.7m -I/usr/local/include -I/usr/include -I/home/rosella/anaconda3/include -I/home/rosella/anaconda3/include/python3.7m -c'
  extra options: '-DNDEBUG -DUSE_BLAS_LIB -fPIC -m64 -fopenmp'
  gcc: spams_wrap/spams_wrap.cpp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /tmp/pip-build-env-5t4ly4vk/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                   from /tmp/pip-build-env-5t4ly4vk/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /tmp/pip-build-env-5t4ly4vk/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from spams_wrap/spams.h:458,
                   from spams_wrap/spams_wrap.cpp:3571:
  /tmp/pip-build-env-5t4ly4vk/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  spams_wrap/spams_wrap.cpp: In function ‘PyObject* PyInit__spams_wrap()’:
  spams_wrap/spams_wrap.cpp:25335:17: warning: variable ‘metatype’ set but not used [-Wunused-but-set-variable]
     PyTypeObject *metatype;
                   ^
  g++ -pthread -shared -B /home/rosella/anaconda3/compiler_compat -L/home/rosella/anaconda3/lib -Wl,-rpath=/home/rosella/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spams_wrap/spams_wrap.o -L/home/rosella/anaconda3/lib -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/lib/ -lstdc++ -lopenblaso -llapack -o build/lib.linux-x86_64-3.7/spams_wrap/_spams_wrap.cpython-37m-x86_64-linux-gnu.so -fopenmp
  /home/rosella/anaconda3/compiler_compat/ld: cannot find -lopenblaso
  collect2: error: ld returned 1 exit status
  /home/rosella/anaconda3/compiler_compat/ld: cannot find -lopenblaso
  collect2: error: ld returned 1 exit status
  error: Command "g++ -pthread -shared -B /home/rosella/anaconda3/compiler_compat -L/home/rosella/anaconda3/lib -Wl,-rpath=/home/rosella/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spams_wrap/spams_wrap.o -L/home/rosella/anaconda3/lib -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/lib/ -lstdc++ -lopenblaso -llapack -o build/lib.linux-x86_64-3.7/spams_wrap/_spams_wrap.cpython-37m-x86_64-linux-gnu.so -fopenmp" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spams
Failed to build spams
ERROR: Could not build wheels for spams which use PEP 517 and cannot be installed directly
```
how could I solve it?
thanks

**Comment by samuelstjean** [comment]
you can try instead this premade version https://pypi.org/project/spams-bin/

**Comment by rosella1234** [comment]
I fear that, even after installing spams-bin, the same issue occurs when trying to install nlsam master version
```
Building wheels for collected packages: spams
  Building wheel for spams (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rosella/anaconda3/bin/python /home/rosella/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp7piwjwck
       cwd: /tmp/pip-install-fazqej3d/spams_d3580a70c0ac46bab5d3a6f467f69df8
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/spams
  copying spams/__init__.py -> build/lib.linux-x86_64-3.7/spams
  copying spams/spams.py -> build/lib.linux-x86_64-3.7/spams
  creating build/lib.linux-x86_64-3.7/spams_wrap
  copying spams_wrap/__init__.py -> build/lib.linux-x86_64-3.7/spams_wrap
  copying spams_wrap/spams_wrap.py -> build/lib.linux-x86_64-3.7/spams_wrap
  running build_ext
  building 'spams_wrap._spams_wrap' extension
  C compiler: gcc -pthread -B /home/rosella/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/spams_wrap
  compile options: '-Ispams_wrap -Ispams_wrap/linalg -Ispams_wrap/prox -Ispams_wrap/decomp -Ispams_wrap/dictLearn -I/tmp/pip-build-env-2_v98dl0/overlay/lib/python3.7/site-packages/numpy/core/include -I/home/rosella/anaconda3/include/python3.7m -I/usr/local/include -I/usr/include -I/home/rosella/anaconda3/include -I/home/rosella/anaconda3/include/python3.7m -c'
  extra options: '-DNDEBUG -DUSE_BLAS_LIB -fPIC -m64 -fopenmp'
  gcc: spams_wrap/spams_wrap.cpp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /tmp/pip-build-env-2_v98dl0/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                   from /tmp/pip-build-env-2_v98dl0/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /tmp/pip-build-env-2_v98dl0/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from spams_wrap/spams.h:458,
                   from spams_wrap/spams_wrap.cpp:3571:
  /tmp/pip-build-env-2_v98dl0/overlay/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  spams_wrap/spams_wrap.cpp: In function ‘PyObject* PyInit__spams_wrap()’:
  spams_wrap/spams_wrap.cpp:25335:17: warning: variable ‘metatype’ set but not used [-Wunused-but-set-variable]
     PyTypeObject *metatype;
                   ^
  g++ -pthread -shared -B /home/rosella/anaconda3/compiler_compat -L/home/rosella/anaconda3/lib -Wl,-rpath=/home/rosella/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spams_wrap/spams_wrap.o -L/home/rosella/anaconda3/lib -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/lib/ -lstdc++ -lopenblaso -llapack -o build/lib.linux-x86_64-3.7/spams_wrap/_spams_wrap.cpython-37m-x86_64-linux-gnu.so -fopenmp
  /home/rosella/anaconda3/compiler_compat/ld: cannot find -lopenblaso
  collect2: error: ld returned 1 exit status
  /home/rosella/anaconda3/compiler_compat/ld: cannot find -lopenblaso
  collect2: error: ld returned 1 exit status
  error: Command "g++ -pthread -shared -B /home/rosella/anaconda3/compiler_compat -L/home/rosella/anaconda3/lib -Wl,-rpath=/home/rosella/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spams_wrap/spams_wrap.o -L/home/rosella/anaconda3/lib -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/lib/ -lstdc++ -lopenblaso -llapack -o build/lib.linux-x86_64-3.7/spams_wrap/_spams_wrap.cpython-37m-x86_64-linux-gnu.so -fopenmp" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spams
Failed to build spams
ERROR: Could not build wheels for spams which use PEP 517 and cannot be installed directly
```
thank you

**Comment by samuelstjean** [comment]
This one is my fault, the setup is not aware of the package yet, if you try the multishell version it should have the updated mechanic in it, which is here https://github.com/samuelstjean/nlsam/archive/refs/heads/multishell.zip

**Comment by rosella1234** [comment]
Does nlsam multishell have the auto option for estimating N and sigma from noise? 
thanks

**Comment by rosella1234** [comment]
Ok I think I managed to install nlsam multishell and it has the 'auto' option in it . thank you
